### ISSUE TITLE
压缩大的文件用解压软件解压报错

### ISSUE THREAD

**Issue by barryzpc** [Viky-zhang/pclzip-doc-zh-cn#1]
你好，当我压缩一个大概有6G的文件夹时，压缩没有报错。但是当我用软件解压的时候就会报错，文件已损坏。我把文件降到3G左右的时候，压缩的文件解压是没有问题的。我想是不是参数设置的问题，我修改了参数还是不行。能给点好的意见吗？

**Comment by vikyd** [comment]
没碰到过这种问题，参考下：
- http://php.net/manual/en/ini.core.php#ini.memory-limit
- https://vikyd.gitbooks.io/pclzip/content/user_guide/optional_arguments.html#pclzipopttempfilethreshold
